/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.room.views;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Telandes Moreira
 */
public class TelaCadUsuario extends javax.swing.JDialog {

    /**
     * Creates new form TelaCadUsuario
     */
    public TelaCadUsuario(java.awt.Dialog parent, boolean modal) {  //jdialog
        super(parent, modal);
        setUndecorated(true);
        initComponents();
    }

    public JButton getjButtonCadastrar() {
        return jButtonCadastrar;
    }

    public JButton getjButtonCancelar() {
        return jButtonCancelar;
    }
    
    public JRadioButton getjRadioButtonUsuarioAdministrador() {
        return jRadioButtonUsuarioAdministrador;
    }

    public JRadioButton getjRadioButtonUsuarioOperador() {
        return jRadioButtonUsuarioOperador;
    }

    public JPasswordField getjPasswordFieldChaveSeguranca() {
        return jPasswordFieldChaveSeguranca;
    }

    public JTextField getjTextFieldNomeUsuario() {
        return jTextFieldNomeUsuario;
    }

    public JTextField getjTextFieldSenha() {
        return jTextFieldSenha;
    }
    
    public void limparCampos(){
        this.jTextFieldNomeUsuario.setText("");
        this.jTextFieldSenha.setText("");
        this.jRadioButtonUsuarioAdministrador.setSelected(false);
        this.jRadioButtonUsuarioOperador.setSelected(false);
        this.jPasswordFieldChaveSeguranca.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelChaveSeguranca = new javax.swing.JLabel();
        jTextFieldNomeUsuario = new javax.swing.JTextField();
        jTextFieldSenha = new javax.swing.JTextField();
        jPasswordFieldChaveSeguranca = new javax.swing.JPasswordField();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jRadioButtonUsuarioOperador = new javax.swing.JRadioButton();
        jRadioButtonUsuarioAdministrador = new javax.swing.JRadioButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro do usuário");
        setResizable(false);
        setSize(new java.awt.Dimension(750, 450));

        jPanel1.setBackground(new java.awt.Color(64, 64, 64));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabelNomeUsuario.setBackground(new java.awt.Color(64, 64, 64));
        jLabelNomeUsuario.setForeground(new java.awt.Color(235, 235, 235));
        jLabelNomeUsuario.setText("Nome de usuário:");

        jLabelSenha.setBackground(new java.awt.Color(64, 64, 64));
        jLabelSenha.setForeground(new java.awt.Color(235, 235, 235));
        jLabelSenha.setText("Senha:");

        jLabelChaveSeguranca.setBackground(new java.awt.Color(64, 64, 64));
        jLabelChaveSeguranca.setForeground(new java.awt.Color(235, 235, 235));
        jLabelChaveSeguranca.setText("Chave de segurança:");

        jTextFieldNomeUsuario.setBackground(new java.awt.Color(235, 235, 235));
        jTextFieldNomeUsuario.setForeground(new java.awt.Color(64, 64, 64));
        jTextFieldNomeUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jTextFieldSenha.setBackground(new java.awt.Color(235, 235, 235));
        jTextFieldSenha.setForeground(new java.awt.Color(64, 64, 64));
        jTextFieldSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jPasswordFieldChaveSeguranca.setBackground(new java.awt.Color(235, 235, 235));
        jPasswordFieldChaveSeguranca.setForeground(new java.awt.Color(64, 64, 64));
        jPasswordFieldChaveSeguranca.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabelTipoUsuario.setBackground(new java.awt.Color(64, 64, 64));
        jLabelTipoUsuario.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTipoUsuario.setText("Tipo de usuário:");

        jRadioButtonUsuarioOperador.setBackground(new java.awt.Color(64, 64, 64));
        buttonGroup1.add(jRadioButtonUsuarioOperador);
        jRadioButtonUsuarioOperador.setForeground(new java.awt.Color(235, 235, 235));
        jRadioButtonUsuarioOperador.setText("Usuário-operador");

        jRadioButtonUsuarioAdministrador.setBackground(new java.awt.Color(64, 64, 64));
        buttonGroup1.add(jRadioButtonUsuarioAdministrador);
        jRadioButtonUsuarioAdministrador.setForeground(new java.awt.Color(235, 235, 235));
        jRadioButtonUsuarioAdministrador.setText("Usuário-administrador");
        jRadioButtonUsuarioAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUsuarioAdministradorActionPerformed(evt);
            }
        });

        jButtonCadastrar.setBackground(new java.awt.Color(235, 235, 235));
        jButtonCadastrar.setForeground(new java.awt.Color(64, 64, 64));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.setBorder(null);

        jButtonCancelar.setBackground(new java.awt.Color(235, 235, 235));
        jButtonCancelar.setForeground(new java.awt.Color(64, 64, 64));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorder(null);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/room/views/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPasswordFieldChaveSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(471, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonUsuarioAdministrador)
                            .addComponent(jLabelChaveSeguranca)
                            .addComponent(jLabelTipoUsuario)
                            .addComponent(jRadioButtonUsuarioOperador)
                            .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSenha)
                            .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNomeUsuario))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTipoUsuario)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonUsuarioOperador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonUsuarioAdministrador)
                .addGap(18, 18, 18)
                .addComponent(jLabelChaveSeguranca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldChaveSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonUsuarioAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUsuarioAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonUsuarioAdministradorActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadUsuario dialog = new TelaCadUsuario(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelChaveSeguranca;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldChaveSeguranca;
    private javax.swing.JRadioButton jRadioButtonUsuarioAdministrador;
    private javax.swing.JRadioButton jRadioButtonUsuarioOperador;
    private javax.swing.JTextField jTextFieldNomeUsuario;
    private javax.swing.JTextField jTextFieldSenha;
    // End of variables declaration//GEN-END:variables
}
