/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.room.views;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Telandes Moreira
 */
public class TelaCadResevas extends javax.swing.JDialog {
    
    private final DefaultTableModel modelo; 

    /**
     * Creates new form TelaResevarQuartos
     */
    public TelaCadResevas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        this.modelo = (DefaultTableModel)jTableIdCategoria.getModel();
        
        while (this.jTextFieldPesquisar.getText().equals("")) {
            this.jTextFieldPesquisar.setText("Informe o valor do id do quarto...");
            this.jTextFieldPesquisar.setEditable(false);
            this.jButtonPesquisar.setEnabled(false);
        }
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public JButton getjButtonPesquisar() {
        return jButtonPesquisar;
    }    
    
    public JButton getjButtonReservar() {
        return jButtonReservar;
    }

    public JButton getjButtonVoltar() {
        return jButtonVoltar;
    }
    
    public JRadioButton getjRadioButtonLivres() {
        return jRadioButtonLivres;
    }

    public JRadioButton getjRadioButtonEmManutencao() {
        return jRadioButtonEmManutencao;
    }

    public JRadioButton getjRadioButtonOcupados() {
        return jRadioButtonOcupados;
    }

    public JRadioButton getjRadioButtonReservados() {
        return jRadioButtonReservados;
    }

    public JTextField getjTextFieldPesquisar() {
        return jTextFieldPesquisar;
    }
    
    public JTable getjTableIdCategoria() {
        return jTableIdCategoria;
    }

    public void adicionarItemTabela(Object... objects){
        this.modelo.addRow(objects);
    }
    
    public void adicionarInformacoesQuarto(String msg){   
        this.jTextAreaInfoQuarto.setText(msg);
    }

    public void limparTela(){           //limpar os outros campos;
        this.jTextFieldPesquisar.setText("Informe o valor do id do quarto");
        this.jTextFieldPesquisar.setEditable(false);
        this.jButtonPesquisar.setEnabled(false);
        this.jTextAreaInfoQuarto.setText("");
        this.limpaTabela();
    }
    
    public void limpaTabela(){
        int linhas = this.modelo.getRowCount(); //tem q ser assim;
        for(int i=0; i<linhas; i++){
            this.modelo.removeRow(0);
        }
    }
    
    public void limparSelecaoRadioButtons() {
        this.buttonGroup1.clearSelection();
        this.jButtonReservar.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonReservar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIdCategoria = new javax.swing.JTable();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jRadioButtonLivres = new javax.swing.JRadioButton();
        jRadioButtonOcupados = new javax.swing.JRadioButton();
        jRadioButtonReservados = new javax.swing.JRadioButton();
        jRadioButtonEmManutencao = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaInfoQuarto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(63, 63, 65));
        setBounds(new java.awt.Rectangle(100, 150, 800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(64, 64, 64));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 550));

        jButtonReservar.setBackground(new java.awt.Color(235, 235, 235));
        jButtonReservar.setForeground(new java.awt.Color(40, 40, 40));
        jButtonReservar.setText("Reservar");
        jButtonReservar.setBorder(null);
        jButtonReservar.setEnabled(false);
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });

        jButtonVoltar.setBackground(new java.awt.Color(235, 235, 235));
        jButtonVoltar.setForeground(new java.awt.Color(40, 40, 40));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setBorder(null);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(80, 80, 80));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(235, 235, 235));
        jScrollPane2.setToolTipText("");

        jTableIdCategoria.setBackground(new java.awt.Color(80, 80, 80));
        jTableIdCategoria.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jTableIdCategoria.setForeground(new java.awt.Color(235, 235, 235));
        jTableIdCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableIdCategoria.setGridColor(new java.awt.Color(40, 40, 40));
        jTableIdCategoria.setRequestFocusEnabled(false);
        jTableIdCategoria.setSelectionBackground(new java.awt.Color(40, 40, 40));
        jTableIdCategoria.setSelectionForeground(new java.awt.Color(235, 235, 235));
        jScrollPane2.setViewportView(jTableIdCategoria);

        jTextFieldPesquisar.setBackground(new java.awt.Color(235, 235, 235));
        jTextFieldPesquisar.setForeground(new java.awt.Color(40, 40, 40));
        jTextFieldPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPesquisarMouseClicked(evt);
            }
        });

        jButtonPesquisar.setBackground(new java.awt.Color(235, 235, 235));
        jButtonPesquisar.setForeground(new java.awt.Color(64, 64, 64));
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/room/views/images/search.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.setBorder(null);

        jRadioButtonLivres.setBackground(new java.awt.Color(64, 64, 64));
        buttonGroup1.add(jRadioButtonLivres);
        jRadioButtonLivres.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jRadioButtonLivres.setForeground(new java.awt.Color(235, 235, 235));
        jRadioButtonLivres.setText("Livres");
        jRadioButtonLivres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLivresActionPerformed(evt);
            }
        });

        jRadioButtonOcupados.setBackground(new java.awt.Color(64, 64, 64));
        buttonGroup1.add(jRadioButtonOcupados);
        jRadioButtonOcupados.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jRadioButtonOcupados.setForeground(new java.awt.Color(235, 235, 235));
        jRadioButtonOcupados.setText("Ocupados");
        jRadioButtonOcupados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOcupadosActionPerformed(evt);
            }
        });

        jRadioButtonReservados.setBackground(new java.awt.Color(64, 64, 64));
        buttonGroup1.add(jRadioButtonReservados);
        jRadioButtonReservados.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jRadioButtonReservados.setForeground(new java.awt.Color(235, 235, 235));
        jRadioButtonReservados.setText("Reservados");
        jRadioButtonReservados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonReservadosActionPerformed(evt);
            }
        });

        jRadioButtonEmManutencao.setBackground(new java.awt.Color(64, 64, 64));
        buttonGroup1.add(jRadioButtonEmManutencao);
        jRadioButtonEmManutencao.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jRadioButtonEmManutencao.setForeground(new java.awt.Color(235, 235, 235));
        jRadioButtonEmManutencao.setText("Em manutenção");
        jRadioButtonEmManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmManutencaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 235, 235));
        jLabel1.setText("Info. do quarto:");

        jTextAreaInfoQuarto.setEditable(false);
        jTextAreaInfoQuarto.setBackground(new java.awt.Color(80, 80, 80));
        jTextAreaInfoQuarto.setColumns(20);
        jTextAreaInfoQuarto.setForeground(new java.awt.Color(235, 235, 235));
        jTextAreaInfoQuarto.setRows(5);
        jTextAreaInfoQuarto.setBorder(null);
        jScrollPane3.setViewportView(jTextAreaInfoQuarto);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home/room/views/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonLivres)
                        .addGap(65, 65, 65)
                        .addComponent(jRadioButtonReservados))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonOcupados)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButtonEmManutencao)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(496, 496, 496)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonLivres)
                    .addComponent(jRadioButtonReservados))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonOcupados)
                    .addComponent(jRadioButtonEmManutencao)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonEmManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmManutencaoActionPerformed
        this.jButtonReservar.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonEmManutencaoActionPerformed

    private void jRadioButtonReservadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonReservadosActionPerformed
        this.jButtonReservar.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonReservadosActionPerformed

    private void jRadioButtonOcupadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOcupadosActionPerformed
        this.jButtonReservar.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonOcupadosActionPerformed

    private void jRadioButtonLivresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLivresActionPerformed
        this.jButtonReservar.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonLivresActionPerformed

    private void jTextFieldPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarMouseClicked
        this.jTextFieldPesquisar.setText("");
        this.jTextFieldPesquisar.setEditable(true);
        this.jButtonPesquisar.setEnabled(true);
    }//GEN-LAST:event_jTextFieldPesquisarMouseClicked

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadResevas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadResevas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadResevas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadResevas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCadResevas dialog = new TelaCadResevas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonEmManutencao;
    private javax.swing.JRadioButton jRadioButtonLivres;
    private javax.swing.JRadioButton jRadioButtonOcupados;
    private javax.swing.JRadioButton jRadioButtonReservados;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableIdCategoria;
    private javax.swing.JTextArea jTextAreaInfoQuarto;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables

}
